apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
    
      containers:
        - name: rabbitmq
          image: mycontregis.azurecr.io/rabbitmq:latest
          ports:
            - containerPort: 80
                   
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 80
   

