apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
    
      containers:
        - name: rabbitmq
          image: mycontregis.azurecr.io/rabbitmq:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: rabbitmq-plugins
              mountPath: /plugins
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
          env:
            - name: RABBITMQ_PLUGINS
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: enabled_plugin
      volumes:
        - name: rabbitmq-plugins
          configMap:
            name: rabbitmq-plugins
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
          
      imagePullSecrets:
        - name: credentials            
                   
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-plugins
data:
  rabbitmq_database_sync.ez: <base64-encoded-plugin-file>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugin: |-
    rabbitmq_management
    rabbitmq_database_sync
   

