apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
spec:
  selector:
    matchLabels:
      app: catalogapi
  replicas: 3
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
      - name: catalogapi
        image: catalogiiregistry.azurecr.io/catalogapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalogapi
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer