apiVersion: v1
kind: Service
metadata:
  name: ordering-api
spec:
  selector:
    app: ordering-api

  ports:
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer
 
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
        - name: ordering-api
          image: mycontregis.azurecr.io/orderingapi:latest
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: credentials

