apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-service
spec:
  selector:
    matchLabels:
      app: discount-service
  replicas: 3
  template:
    metadata:
      labels:
        app: discount-service
    spec:
      containers:
      - name: discount-service
        image: my-registry/discount-service:latest
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: POSTGRES_HOST
          value: postgresql-service
        - name: POSTGRES_PORT
          value: "5432"
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: discount-service
spec:
  selector:
    app: discount-service
  ports:
  - name: http
    port: 80
    targetPort: http
